---
global_variables:
  user_list:
  - "Axel"
  - "Lana"
  - "Carl"
  - "Lorenzo"
  raw_data_server: "\\\\sv-nas1.rcp.epfl.ch\\ptbiop-raw\\temp-Lorenzo\\Petersen-Lab\\\
    data"
  analysis_server: "\\\\sv-nas1.rcp.epfl.ch\\ptbiop-raw\\temp-Lorenzo\\Petersen-Lab\\\
    analysis"
  use_fast_reader: false
  resave_in_hdf5: false
  use_fast_fusion: true
  fusion_method: "SMOOTH AVERAGE"
general_parameters:
  user: ""
  input_folders:
  - "Select CZI folder or folders"
  output_dir: "Select output folder"
  parent_yaml_parameter_file: ""
  processing_yaml_parameter_file: ""
  save_2D: false
  save_3D: true
  preprocessing: true
  atlas_registration: false
  input_brain_orientation:
  - "sal"
  output_brain_orientation:
  - "asr"
  downsampling: "1"
resaving_parameters:
  subsampling_factors:
  - "{1, 1, 1}"
  - "{2, 2, 1}"
  - "{4, 4, 2}"
  - "{8, 8, 4}"
  - "{16, 16, 8}"
  hdf5_chunk_sizes:
  - "{32, 32, 32}"
  - "{32, 32, 32}"
  - "{32, 32, 32}"
  - "{32, 32, 32}"
  - "{32 ,32, 32}"
channel_alignment_parameters:
  pairwise_shifts_downsamples_XYZ:
  - 2
  - 2
  - 1
  filter_min_r: 0.7
  optimize_fix_group: "fix_group_0-10"
tile_alignment_parameters:
  pairwise_shifts_parameters:
  - "group"
  - "use Channel 488"
  - - 4
    - 4
    - 2
  filter_min_r: 0.7
  optimize_fix_group: "fix_group_0-10"
icp_refinement_parameters:
  icp_refinement_type: "Simple (all together)"
  downsampling: "Downsampling 8/8/4"
  interest: "Average Threshold"
  icp_max_error: "Normal Adjustment (<5px)"
fusion_parameters:
  preserve_original: "preserve_original"
  produce: "Each timepoint & channel"
  fused_image: "Save as (compressed) TIFF stacks"
  filename_addition: ""
